name: "Twitch Drops Miner"
description: "AFK mine timed Twitch drops with automatic drop claiming and channel switching"
version: "v16.dev.090e59c"
slug: "twitch_drops_miner"
url: "https://github.com/DarkAssassinUA/HA-Addons"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 5800
panel: true
panel_icon: "mdi:pickaxe"
ports:
  5800/tcp: 5800
map:
  - addon_config:rw
options: {}
schema: {}