name: Check for updates

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:      # Возможность ручного запуска из интерфейса GitHub

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Разрешение на запись для коммита и пуша изменений
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check and update version
        run: python update_addon.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git add twitch_drops_miner/config.yaml twitch_drops_miner/docker_digest.txt
            git commit -m "Bump addon version due to Docker image update"
            git push
          else
            echo "No changes to commit"
          fi
